name: semrelease

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    # - name: test
    #   env:
    #     PAT: ${{ secrets.PAT }}
    #   with:
    #     repository: LucasSimoesPolvora/semrelease
    #     token: $PAT 