name: semrelease

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: setup git
      run: |
        git config user.name "action"
        git config user.email "action@test.com"
    - name: Current version ${{ github.ref_name }}
      run: echo "hello world I need the tag"
