name: semrelease

on:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]'
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: setup git
      run: |
        git config user.name "action"
        git config user.email "action@test.com"
    - name: fetch tags
      run: git fetch --tags
